import React, { useState } from 'react';
import * as Haptics from 'expo-haptics';
import { Ionicons } from '@expo/vector-icons';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Header, Label, PrimaryButton, Screen, Surface } from '@/components/Primitives';
import { ResponseCheckInput, ResponseCheckResult, checkEndpoint } from '@/services/responseChecker';
import { useColors } from '@/hooks/useColors';

const EMPTY_INPUT: ResponseCheckInput = { host: '', port: '', sni: '', proxyHost: '', proxyPort: '', customHeaders: '', method: 'GET' };
const METHODS: ResponseCheckInput['method'][] = ['GET', 'POST', 'HEAD', 'DELETE', 'OPTIONS', 'PATCH'];

export default function ResponseCheckerScreen() {
  const colors = useColors();
  const router = useRouter();
  const [input, setInput] = useState<ResponseCheckInput>(EMPTY_INPUT);
  const [result, setResult] = useState<ResponseCheckResult | null>(null);
  const [checking, setChecking] = useState(false);
  const update = (key: keyof ResponseCheckInput, value: string) => setInput((current) => ({ ...current, [key]: value }));
  const check = async () => { if (!input.host.trim()) return; setChecking(true); setResult(null); Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light).catch(() => undefined); const next = await checkEndpoint(input); setResult(next); setChecking(false); };
  const field = (key: keyof ResponseCheckInput, placeholder: string, extra?: object) => <TextInput value={String(input[key])} onChangeText={(value) => update(key, value)} placeholder={placeholder} placeholderTextColor={colors.mutedForeground} autoCapitalize="none" style={[styles.input, { color: colors.foreground, borderColor: colors.border, backgroundColor: colors.secondary }, extra]} />;
  return <Screen><Header eyebrow="Diagnostics" title="Response Checker" action="BACK" onAction={() => router.back()} />
    <Surface style={styles.intro}><Ionicons name="shield-checkmark-outline" size={22} color={colors.primary} /><View style={{ flex: 1 }}><Text style={[styles.introTitle, { color: colors.foreground }]}>Authorized endpoints only</Text><Text style={[styles.introText, { color: colors.mutedForeground }]}>Check reachability without claiming that an HTTP response is a working VPN tunnel.</Text></View></Surface>
    <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Endpoint</Text>
    {field('host', 'Host / URL')}<View style={styles.inputRow}>{field('port', 'Port', styles.smallInput)}{field('sni', 'SNI / Server Name', styles.largeInput)}</View><View style={styles.inputRow}>{field('proxyHost', 'Proxy host', styles.largeInput)}{field('proxyPort', 'Proxy port', styles.smallInput)}</View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>HTTP method</Text><View style={styles.methodWrap}>{METHODS.map((method) => <Pressable key={method} onPress={() => setInput((current) => ({ ...current, method }))} style={[styles.method, { backgroundColor: input.method === method ? colors.accent : colors.secondary, borderColor: input.method === method ? colors.primary : colors.border }]}><Text style={[styles.methodText, { color: input.method === method ? colors.primary : colors.mutedForeground }]}>{method}</Text></Pressable>)}</View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Custom headers</Text>{field('customHeaders', 'Header: value (one per line)', styles.multiline)}<View style={styles.checkButton}><PrimaryButton title={checking ? 'CHECKING…' : 'CHECK'} icon="pulse" onPress={() => { void check(); }} disabled={checking || !input.host.trim()} /></View>{checking ? <ActivityIndicator color={colors.primary} style={styles.loader} /> : null}
    {result ? <Surface style={[styles.result, { borderColor: result.reachable ? colors.success : colors.primary }]}><View style={styles.resultHeader}><View><Label>Result</Label><Text style={[styles.resultStatus, { color: result.reachable ? colors.success : colors.primary }]}>{result.reachable ? 'ONLINE' : 'UNREACHABLE'}</Text></View><Ionicons name={result.reachable ? 'checkmark-circle' : 'close-circle'} size={28} color={result.reachable ? colors.success : colors.primary} /></View><View style={styles.resultGrid}><ResultCell label="HTTP" value={result.statusCode ? String(result.statusCode) : '—'} /><ResultCell label="RESPONSE" value={result.responseTime === null ? '—' : result.responseTime + ' ms'} /><ResultCell label="TLS" value={result.tlsStatus} /><ResultCell label="SNI" value={result.hostnameResult} /><ResultCell label="REDIRECT" value={result.redirect} /></View>{result.headers.length ? <Text style={[styles.headers, { color: colors.mutedForeground }]}>{result.headers.join('\\n')}</Text> : null}{result.error ? <Text style={[styles.error, { color: colors.primary }]}>{result.error}</Text> : null}</Surface> : null}
  </Screen>;
}

function ResultCell({ label, value }: { label: string; value: string }) { const colors = useColors(); return <View style={styles.resultCell}><Text style={[styles.resultLabel, { color: colors.mutedForeground }]}>{label}</Text><Text style={[styles.resultValue, { color: colors.foreground }]}>{value}</Text></View>; }

const styles = StyleSheet.create({ intro: { flexDirection: 'row', gap: 12, alignItems: 'flex-start' }, introTitle: { fontFamily: 'Inter_700Bold', fontSize: 14 }, introText: { fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 18, marginTop: 4 }, sectionTitle: { fontFamily: 'Inter_700Bold', fontSize: 17, marginTop: 24, marginBottom: 10 }, input: { minHeight: 51, borderWidth: 1, borderRadius: 15, paddingHorizontal: 14, fontFamily: 'Inter_400Regular', fontSize: 13, marginTop: 10 }, inputRow: { flexDirection: 'row', gap: 10 }, smallInput: { flex: 0.6 }, largeInput: { flex: 1 }, methodWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, method: { borderRadius: 13, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 10 }, methodText: { fontFamily: 'Inter_600SemiBold', fontSize: 11 }, multiline: { minHeight: 92, textAlignVertical: 'top', paddingTop: 14 }, checkButton: { marginTop: 20 }, loader: { marginTop: 14 }, result: { marginTop: 20, borderWidth: 1 }, resultHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, resultStatus: { fontFamily: 'Inter_700Bold', fontSize: 24, marginTop: 5 }, resultGrid: { gap: 12, marginTop: 18 }, resultCell: { gap: 4 }, resultLabel: { fontFamily: 'Inter_600SemiBold', fontSize: 10, letterSpacing: 0.8 }, resultValue: { fontFamily: 'Inter_500Medium', fontSize: 13, lineHeight: 18 }, headers: { fontFamily: 'Inter_400Regular', fontSize: 11, lineHeight: 17, marginTop: 16 }, error: { fontFamily: 'Inter_500Medium', fontSize: 12, lineHeight: 18, marginTop: 16 },
});
